apiVersion: v2
name: flux2
description: A Helm chart for flux2
type: application
version: 0.16.0
appVersion: 0.28.3
sources:
  - https://github.com/fluxcd-community/helm-charts
annotations:
  artifacthub.io/changes: |
    - "[Update]: Add podMonitor creation for the Prometheus Operator"
